[package]
name = "projekt-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
tokio-rusqlite = "0.5.1"
jsonwebtoken = "=7.2"
time = "0.3.34"
