version: '3'

services:
  backend:
    image: backend:latest
    container_name: backend
    restart: always
    networks:
      - default
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./media:/usr/src/backend/media

networks:
  default:
    external: true
    name: main
