version: '3'

services:
  backend:
    image: backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./media:/usr/src/backend/media
