DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS users;

CREATE TABLE posts(
	user_id INTEGER NOT NULL,
	body VARCHAR(2048) NOT NULL
);

CREATE TABLE posts(
	user_id INTEGER PRIMARY KEY NOT NULL,
	user_name VARCHAR(64) NOT NULL
);

