name: Cargo CI

on:
  push:
    branches: [ main, chlopczyk ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_job:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo build --verbose
